#!/usr/bin/env php
<?php

$loader = require_once 'vendor/autoload.php';
$loader->register();

use Assetic\Asset\AssetCollection;
use Assetic\Asset\FileAsset;
use Assetic\Asset\HttpAsset;
use Assetic\Filter\LessFilter;
use Assetic\Filter\UglifyCssFilter;
use Assetic\Filter\Sass\SassFilter;
use Assetic\Filter\UglifyJsFilter;

$less = new LessFilter('/usr/bin/nodejs', array('/usr/local/lib/node_modules'));
$sass = new SassFilter();
$uglifyCss = new UglifyCssFilter('/usr/local/bin/uglifycss', '/usr/bin/nodejs');

$css = new AssetCollection(array(
    new FileAsset('src/assets/css/bootstrap.less', array($less)),
    new HttpAsset('//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css'),
    new FileAsset('src/assets/css/styles.scss', array($sass)),
),
    array($uglifyCss)
);
file_put_contents('web/all.css', $css->dump());

$uglifyJs = new UglifyJsFilter('/usr/local/bin/uglifyjs', '/usr/bin/nodejs');
$js = new AssetCollection(array(
    new HttpAsset('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'),
    new FileAsset('src/assets/js/bootstrap.min.js'),
    new FileAsset('src/assets/js/main.js'),
),
    array($uglifyJs)
);
file_put_contents('web/all.js', $js->dump());
